service: ${file(./package.json):name}

frameworkVersion: "2"
plugins:
  - serverless-dotenv-plugin

custom:
  bucket: "${self:service}--final-assets"

provider:
  name: aws
  profile: sls
  region: eu-west-2
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  individually: true

functions:
  remove-bg:
    handler: removeBg.handler
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    NoBgAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
